# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65d77249ac53baf411bb6003b7b6d5dc62aacdffefe94d25847b68686e165a35e82b338798fce89c0a4dae060053754c77853c25e9880e20d67db8f296edad53

test:
  secret_key_base: 40b6f656833bbbbfb96245c2d336a4e4e711284e9e7a94caadb4dfe50e15ed5172dca55efe2484e86324514b01b3b75470d5e7203208e5cf665720ed52762a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
